//
// Generated file, do not edit! Created by opp_msgtool 6.0 from /home/hegde/workspace/main/Artery-C/src/artery/nic/PoiRetrievalModule.msg.
//

#ifndef __ARTERY_POIRETRIEVALMODULE_M_H
#define __ARTERY_POIRETRIEVALMODULE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace artery {

class PoiRetrievalModule;

}  // namespace artery


namespace artery {

/**
 * Class generated from <tt>/home/hegde/workspace/main/Artery-C/src/artery/nic/PoiRetrievalModule.msg:26</tt> by opp_msgtool.
 * <pre>
 * class PoiRetrievalModule
 * {
 *     \@customize(true);
 * }
 * </pre>
 *
 * PoiRetrievalModule_Base is only useful if it gets subclassed, and PoiRetrievalModule is derived from it.
 * The minimum code to be written for PoiRetrievalModule is the following:
 *
 * <pre>
 * class PoiRetrievalModule : public PoiRetrievalModule_Base
 * {
 *   private:
 *     void copy(const PoiRetrievalModule& other) { ... }

 *   public:
 *     PoiRetrievalModule() : PoiRetrievalModule_Base() {}
 *     PoiRetrievalModule(const PoiRetrievalModule& other) : PoiRetrievalModule_Base(other) {copy(other);}
 *     PoiRetrievalModule& operator=(const PoiRetrievalModule& other) {if (this==&other) return *this; PoiRetrievalModule_Base::operator=(other); copy(other); return *this;}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from PoiRetrievalModule_Base
 * };
 * </pre>
 */
class PoiRetrievalModule_Base
{
  protected:

  private:
    void copy(const PoiRetrievalModule_Base& other);

  protected:
    bool operator==(const PoiRetrievalModule_Base&) = delete;
    // make constructors protected to avoid instantiation
    PoiRetrievalModule_Base();
    PoiRetrievalModule_Base(const PoiRetrievalModule_Base& other);
    // make assignment operator protected to force the user override it
    PoiRetrievalModule_Base& operator=(const PoiRetrievalModule_Base& other);

  public:
    virtual ~PoiRetrievalModule_Base();
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);
};


}  // namespace artery


namespace omnetpp {

inline any_ptr toAnyPtr(const artery::PoiRetrievalModule_Base *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline artery::PoiRetrievalModule_Base *fromAnyPtr(any_ptr ptr) { return ptr.get<artery::PoiRetrievalModule_Base>(); }

}  // namespace omnetpp

#endif // ifndef __ARTERY_POIRETRIEVALMODULE_M_H

