name: Feature tests

on:
  schedule:
      # https://crontab.guru/#0_16_*_*_6
    - cron: "0 16 * * 6" # “At 16:00 on Saturday.”
  workflow_dispatch:
    # nothing

jobs:
  featuretests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we could go all the way up to 20 even
        node-index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        node-total: [16] # keep these in sync!
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker image
        run: docker pull ghcr.io/inet-framework/ci-inet:6.0.1-230320
      - name: Feature tests (split)
        run: |
          docker run -i --env SKIPPED_FEATURES="" --env SPLIT_INDEX=${{ matrix.node-index }} --env SPLIT_TOTAL=${{ matrix.node-total }} \
            --env GITHUB_WORKSPACE -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            ghcr.io/inet-framework/ci-inet:6.0.1-230320 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-featuretests.sh
      - uses: actions/upload-artifact@v3
        if: always() # even if the test failed, of course
        with:
          name: log-${{ matrix.node-index }}
          path: ${{ github.workspace }}/tests/features/_log
